Repository adafruit/circuitpython, pull requests merged in 2018-05, with the labels that each got.

#788 (u)binascii: better python3 compatibility
  extmod/modubinascii.c
  py/objmodule.c
  tests/extmod/ubinascii_a2b_base64.py
  tests/extmod/ubinascii_b2a_base64.py
  tests/extmod/ubinascii_crc32.py
  tests/extmod/ubinascii_hexlify.py
  tests/extmod/ubinascii_unhexlify.py
Labels: cpython api, enhancement

#820 Add pause/resume control to AudioOut and I2SOut
  ports/atmel-samd/audio_dma.c
  ports/atmel-samd/audio_dma.h
  ports/atmel-samd/common-hal/audiobusio/I2SOut.c
  ports/atmel-samd/common-hal/audioio/AudioOut.c
  ports/atmel-samd/shared_dma.c
  ports/atmel-samd/shared_dma.h
  shared-bindings/audiobusio/I2SOut.c
  shared-bindings/audiobusio/I2SOut.h
  shared-bindings/audioio/AudioOut.c
  shared-bindings/audioio/AudioOut.h
Labels: atmel-samd, circuitpython api, enhancement

#862 Update CONTRIBUTING.md to include new learn guides and Dan and
  CONTRIBUTING.md
Labels: documentation

#865 Fix ReadTheDocs build due to c2rst.
  docs/c2rst.py
Labels: bug, documentation

#871 Remove asf3 nvm code.
  ports/atmel-samd/supervisor/port.c
Labels: atmel-samd
