Repository adafruit/circuitpython, pull requests merged in 2018-02, with the labels that each got.

#599 Update conf.py for new ports and port location.
  conf.py
Labels: documentation

#618 nrf: Use -O1 for debug builds
  ports/nrf/Makefile
Labels: nrf52

#617 nrf: Change pin names on DKs to match silkscreen
  ports/nrf/Makefile
  ports/nrf/boards/feather52/mpconfigboard.h
  ports/nrf/boards/feather52/pins.c
  ports/nrf/boards/feather52/pins.csv
  ports/nrf/boards/feather52/pins.h
  ports/nrf/boards/make-pins.py
  ports/nrf/boards/nrf52_prefix.c
  ports/nrf/boards/pca10040/mpconfigboard.h
  ports/nrf/boards/pca10040/pins.c
  ports/nrf/boards/pca10040/pins.csv
  ports/nrf/boards/pca10040/pins.h
  ports/nrf/boards/pca10056/mpconfigboard.h
  ports/nrf/boards/pca10056/pins.c
  ports/nrf/boards/pca10056/pins.csv
  ports/nrf/boards/pca10056/pins.h
  ports/nrf/modules/machine/pin.h
  ports/nrf/nrf52_af.csv
  ports/nrf/pin_defs_nrf5.h
Labels: nrf52

#600 Clarify style of attribute comments in the Design Guide.
  docs/design_guide.rst
  shared-bindings/analogio/AnalogIn.c
  shared-bindings/analogio/AnalogOut.c
  shared-bindings/audioio/AudioOut.c
  shared-bindings/digitalio/DigitalInOut.c
  shared-bindings/microcontroller/Processor.c
  shared-bindings/pulseio/PulseIn.c
  shared-bindings/touchio/TouchIn.c
  shared-bindings/usb_hid/Device.c
Labels: core api, documentation

#621 Increase the status LED brightness a bit so that newer DotStars
  atmel-samd/rgb_led_colors.h
  atmel-samd/rgb_led_status.c
Labels: atmel-samd, enhancement
