Repository adafruit/circuitpython, pull requests merged in 2018-07, with the labels that each got.

#972 nrf: Rewrite the I2C common-hal using nrfx
  ports/nrf/Makefile
  ports/nrf/common-hal/busio/I2C.c
  ports/nrf/common-hal/busio/I2C.h
  ports/nrf/nrfx_config.h
Labels: nrf52

#982 nrf: Save some flash bytes by using extra compile flags
  ports/nrf/Makefile
Labels: nrf52

#991 nrf: Fix SPI transfers with data larger than HW allows
  ports/nrf/common-hal/busio/SPI.c
Labels: bug, nrf52

#992 nrf: Fix I2C transfers with data larger than HW allows
  ports/nrf/common-hal/busio/I2C.c
Labels: bug, nrf52

#999 nrf: mphalport cleanup
  ports/nrf/mphalport.h
Labels: nrf52

#1000 nrf: Rewrite the UART HAL using nRFx
  ports/nrf/Makefile
  ports/nrf/boards/feather52832/mpconfigboard.h
  ports/nrf/boards/feather52840/mpconfigboard.h
  ports/nrf/boards/pca10040/mpconfigboard.h
  ports/nrf/boards/pca10056/mpconfigboard.h
  ports/nrf/hal/hal_uart.c
  ports/nrf/hal/hal_uart.h
  ports/nrf/help.c
  ports/nrf/mpconfigport.h
  ports/nrf/mphalport.c
  ports/nrf/mphalport.h
  ports/nrf/nrfx_config.h
  ports/nrf/supervisor/serial.c
Labels: nrf52

#985 A few heap related tweaks
  .gitignore
  lib/utils/pyexec.c
  main.c
  ports/atmel-samd/Makefile
  ports/atmel-samd/supervisor/samd21_cpu.s
  ports/atmel-samd/supervisor/samd51_cpu.s
  ports/nrf/Makefile
  ports/nrf/supervisor/cpu.s
  py/builtinimport.c
  py/gc.c
  py/gc_long_lived.c
  py/mpconfig.h
  py/qstr.c
  supervisor/cpu.h
  tools/analyze_heap_dump.py
  tools/output_gc_until_repl.txt
Labels: memory optimization

#1002 nrf: Rewrite the DigitalInOut hal using nRFx
  ports/nrf/common-hal/analogio/AnalogIn.c
  ports/nrf/common-hal/digitalio/DigitalInOut.c
  ports/nrf/common-hal/digitalio/DigitalInOut.h
  ports/nrf/common-hal/microcontroller/Pin.c
  ports/nrf/common-hal/microcontroller/Pin.h
  ports/nrf/common-hal/pulseio/PWMOut.c
  ports/nrf/hal/hal_gpio.h
  ports/nrf/mphalport.h
Labels: nrf52

#1011 nrf: More cleanup and porting
  ports/nrf/Makefile
  ports/nrf/boards/feather52832/nrf52_hal_conf.h
  ports/nrf/boards/feather52840/nrf52_hal_conf.h
  ports/nrf/boards/pca10040/nrf52_hal_conf.h
  ports/nrf/boards/pca10056/nrf52_hal_conf.h
  ports/nrf/common-hal/time/__init__.c
  ports/nrf/drivers/bluetooth/ble_uart.c
  ports/nrf/drivers/softpwm.c
  ports/nrf/drivers/softpwm.h
  ports/nrf/drivers/ticker.c
  ports/nrf/drivers/ticker.h
  ports/nrf/fifo.c
  ports/nrf/fifo.h
  ports/nrf/gccollect.h
  ports/nrf/hal/hal_rng.c
  ports/nrf/hal/hal_rng.h
  ports/nrf/hal/hal_time.c
  ports/nrf/hal/hal_time.h
  ports/nrf/hal/nrf52_hal.h
  ports/nrf/modules/random/modrandom.c
  ports/nrf/modules/ubluepy/ubluepy_scanner.c
  ports/nrf/mpconfigport.h
  ports/nrf/mphalport.c
  ports/nrf/mphalport.h
Labels: nrf52

#1022 nrf: Fix BLE on nRF52840 after adding the USB functionality
  ports/nrf/drivers/bluetooth/ble_drv.c
Labels: bug, nrf52

#1023 nrf: Fix flashing with pyocd
  ports/nrf/Makefile
Labels: nrf52

#1014 nrf: Split the ble module into a shared part and the port implementation
  ports/nrf/Makefile
  ports/nrf/bluetooth_conf.h
  ports/nrf/common-hal/bleio/Adapter.c
  ports/nrf/common-hal/bleio/Adapter.h
  ports/nrf/common-hal/bleio/__init__.c
  ports/nrf/modules/ble/modble.c
  ports/nrf/mpconfigport.h
  shared-bindings/bleio/Adapter.c
  shared-bindings/bleio/Adapter.h
  shared-bindings/bleio/__init__.c
  shared-bindings/bleio/__init__.h
  shared-bindings/index.rst
Labels: nrf52

#1075 Use more mp_raise_* to save 28 bytes code size.
  shared-bindings/microcontroller/Pin.c
  shared-bindings/neopixel_write/__init__.c
  shared-bindings/pulseio/PulseOut.c
  shared-module/bitbangio/SPI.c
Labels: memory optimization
