Repository adafruit/circuitpython, pull requests merged in 2018-12, with the labels that each got.

#1347 Update for Grand Central Rev B
  .travis.yml
  ports/atmel-samd/boards/grandcentral_m4_express/mpconfigboard.h
  ports/atmel-samd/boards/grandcentral_m4_express/pins.c
Labels: atmel-samd, enhancement

#1372 UART changes: timeout in secs, write bytes, etc.
  locale/circuitpython.pot
  locale/de_DE.po
  locale/en_US.po
  locale/es.po
  locale/fil.po
  locale/fr.po
  locale/it_IT.po
  locale/pt_BR.po
  ports/atmel-samd/common-hal/busio/UART.c
  ports/esp8266/common-hal/busio/UART.c
  ports/nrf/common-hal/busio/UART.c
  py/stream.c
  py/stream.h
  shared-bindings/busio/I2C.c
  shared-bindings/busio/UART.c
  shared-bindings/busio/UART.h
Labels: circuitpython api, enhancement

#1344 Add Mini SAM M4 board.
  .travis.yml
  ports/atmel-samd/boards/mini_sam_m4/board.c
  ports/atmel-samd/boards/mini_sam_m4/mpconfigboard.h
  ports/atmel-samd/boards/mini_sam_m4/mpconfigboard.mk
  ports/atmel-samd/boards/mini_sam_m4/pins.c
  supervisor/shared/external_flash/devices.h
Labels: atmel-samd, enhancement

#1385 Fix running the USB task on nRF.
  main.c
  ports/atmel-samd/background.c
  ports/atmel-samd/mpconfigport.h
  ports/nrf/background.c
Labels: bug, nrf52

#1386 Build UF2s for the particle boards
  tools/build_board_info.py
Labels: enhancement, nrf52, tooling

#1392 Strip a newline from the version tag.
  tools/build_board_info.py
Labels: tooling

#1399 Default nrf boards to UF2
  tools/build_board_info.py
Labels: nrf52, tooling
