Repository adafruit/circuitpython, pull requests merged in 2019-06, with the labels that each got.

#1939 When clearing gamepad buffer, use the last button state, not 0
  shared-bindings/gamepad/GamePad.c
  shared-bindings/gamepadshift/GamePadShift.c
Labels: bug

#1953 Add baudrate to FourWire and shorten delay.
  ports/atmel-samd/boards/hallowing_m0_express/board.c
  ports/atmel-samd/boards/pybadge/board.c
  ports/atmel-samd/boards/pybadge_airlift/board.c
  ports/atmel-samd/boards/pygamer/board.c
  ports/atmel-samd/boards/ugame10/board.c
  shared-bindings/displayio/FourWire.c
  shared-bindings/displayio/FourWire.h
  shared-module/displayio/FourWire.c
Labels: bug, displayio, enhancement

#1952 Fix TileGrid's dirty tracking when changing top left
  shared-module/displayio/TileGrid.c
Labels: bug, displayio

#1959 Documentation fixes.
  Makefile
  docs/library/builtins.rst
  shared-bindings/digitalio/DigitalInOut.c
  shared-bindings/digitalio/Direction.c
  shared-bindings/digitalio/DriveMode.c
  shared-bindings/digitalio/Pull.c
  shared-bindings/displayio/Display.c
  shared-bindings/fontio/Glyph.c
Labels: documentation, enhancement

#1973 Add keep alive to Travis deploy
  .travis.yml
Labels: bug, tooling

#1974 Properly reset the terminal each init.
  supervisor/shared/display.c
Labels: bug, displayio
