Repository adafruit/circuitpython, pull requests merged in 2019-08, with the labels that each got.

#2030 Add support for scaling to _stage
  shared-bindings/_stage/__init__.c
  shared-module/_stage/__init__.c
  shared-module/_stage/__init__.h
Labels: displayio, enhancement

#2040 Merge 4.1.0 into master
  locale/ID.po
  locale/circuitpython.pot
  locale/de_DE.po
  locale/en_US.po
  locale/en_x_pirate.po
  locale/es.po
  locale/fil.po
  locale/fr.po
  locale/it_IT.po
  locale/pl.po
  locale/pt_BR.po
  locale/zh_Latn_pinyin.po
  shared-bindings/displayio/TileGrid.c
  shared-bindings/displayio/TileGrid.h
  shared-module/displayio/Bitmap.c
  shared-module/displayio/Bitmap.h
  shared-module/displayio/TileGrid.c
  shared-module/displayio/TileGrid.h
  supervisor/shared/display.h
  tools/gen_display_resources.py
Labels: circuitpython api, displayio, enhancement

#2042 makeqstrdata: permit longer "compressed" outputs
  py/makeqstrdata.py
Labels: bug, internationalization, tooling

#2053 py: mp_obj_tuple_get: accept any item which can use tuple_getiter
  py/objtuple.c
Labels: bug, cpython api, crash

#2050 usb_hid: Allow USB work to progress while waiting for tud_hid_ready
  shared-module/usb_hid/Device.c
Labels: bug, usb

#2047 Fix Terminal's Tilegrid not Clearing
  shared-module/terminalio/Terminal.c
Labels: bug, displayio

#2063 Fix I2CDisplay lifecycle and splash lifecycle.
  py/circuitpy_mpconfig.h
  shared-module/board/__init__.c
  shared-module/displayio/Display.c
  shared-module/displayio/__init__.c
Labels: bug, displayio, supervisor

#2032 Allow to specify pre-allocated buffer in audicore.WaveFile
  shared-bindings/audiocore/WaveFile.c
  shared-bindings/audiocore/WaveFile.h
  shared-module/audiocore/WaveFile.c
Labels: audioio, enhancement, memory optimization

#2055 Implement and use RUN_BACKGROUND_TASKS in place of MICROPY_VM_HOOK_LOOP
  ports/atmel-samd/common-hal/audiobusio/PDMIn.c
  ports/atmel-samd/common-hal/audioio/AudioOut.c
  ports/atmel-samd/common-hal/busio/UART.c
  ports/atmel-samd/common-hal/pulseio/PulseOut.c
  ports/atmel-samd/common-hal/touchio/TouchIn.c
  ports/atmel-samd/mphalport.c
  ports/nrf/bluetooth/ble_uart.c
  ports/nrf/common-hal/bleio/Central.c
  ports/nrf/common-hal/bleio/Characteristic.c
  ports/nrf/common-hal/bleio/CharacteristicBuffer.c
  ports/nrf/common-hal/busio/UART.c
  ports/nrf/common-hal/neopixel_write/__init__.c
  ports/nrf/common-hal/pulseio/PulseOut.c
  ports/nrf/mphalport.c
  ports/nrf/sd_mutex.c
  py/circuitpy_mpconfig.h
  shared-bindings/_stage/__init__.c
  shared-bindings/displayio/FourWire.c
  shared-bindings/displayio/I2CDisplay.c
  shared-bindings/displayio/ParallelBus.c
  shared-bindings/i2cslave/I2CSlave.c
  shared-module/displayio/Display.c
Labels: enhancement, refactoring

#2027 To displayio.Display: expose fill_area and add a property for rotation
  locale/ID.po
  locale/circuitpython.pot
  locale/de_DE.po
  locale/en_US.po
  locale/en_x_pirate.po
  locale/es.po
  locale/fil.po
  locale/fr.po
  locale/it_IT.po
  locale/pl.po
  locale/pt_BR.po
  locale/zh_Latn_pinyin.po
  ports/atmel-samd/boards/itsybitsy_m0_express/mpconfigboard.mk
  shared-bindings/displayio/Display.c
  shared-bindings/displayio/Display.h
  shared-module/displayio/Display.c
  shared-module/displayio/Display.h
Labels: displayio, enhancement

#2088 Swap the CI to GitHub Actions from Travis
  .github/workflows/build.yml
  .github/workflows/create_website_pr.yml
  .travis.yml
  tools/build_board_info.py
  tools/build_release_files.py
  tools/ci_new_boards_check.py
  tools/travis_new_boards_check.py
  tools/upload_release_files.py
Labels: enhancement, tooling

#2094 Add Hallowing M4 support
  .travis.yml
  ports/atmel-samd/boards/hallowing_m4_express/board.c
  ports/atmel-samd/boards/hallowing_m4_express/mpconfigboard.h
  ports/atmel-samd/boards/hallowing_m4_express/mpconfigboard.mk
  ports/atmel-samd/boards/hallowing_m4_express/pins.c
Labels: atmel-samd, enhancement
