Repository adafruit/circuitpython, pull requests merged in 2019-09, with the labels that each got.

#2105 Add GD25Q32C flash device definition
  supervisor/shared/external_flash/devices.h
Labels: enhancement

#2111 Fix I2CDisplay bus_free to not grab lock
  shared-module/displayio/Display.c
  shared-module/displayio/I2CDisplay.c
Labels: bug, displayio

#2112 Swap to Blinka access token to hopefully not hit rate limit
  .github/workflows/build.yml
  .github/workflows/create_website_pr.yml
Labels: bug, tooling

#2117 Fix transactions in _stage after displayio changes
  shared-bindings/_stage/__init__.c
  shared-module/_stage/__init__.c
Labels: bug, displayio

#2113 Add .hidden to TileGrid and Group
  ports/atmel-samd/boards/ugame10/mpconfigboard.mk
  shared-bindings/displayio/Group.c
  shared-bindings/displayio/Group.h
  shared-bindings/displayio/TileGrid.c
  shared-bindings/displayio/TileGrid.h
  shared-bindings/displayio/__init__.h
  shared-module/displayio/Display.c
  shared-module/displayio/Group.c
  shared-module/displayio/Group.h
  shared-module/displayio/I2CDisplay.c
  shared-module/displayio/TileGrid.c
  shared-module/displayio/TileGrid.h
  supervisor/shared/display.c
  tools/gen_display_resources.py
Labels: bug, displayio, enhancement

#2120 Fix website updater for other users.
  tools/build_board_info.py
Labels: bug, tooling

#2121 Add support for converting autolinks to BBCode
  tools/convert_release_notes.py
Labels: enhancement, tooling

#2163 Add custom CPX build for display support
  .github/workflows/build.yml
  ports/atmel-samd/boards/circuitplayground_express_displayio/board.c
  ports/atmel-samd/boards/circuitplayground_express_displayio/mpconfigboard.h
  ports/atmel-samd/boards/circuitplayground_express_displayio/mpconfigboard.mk
  ports/atmel-samd/boards/circuitplayground_express_displayio/pins.c
Labels: atmel-samd, enhancement

#2171 STM32: fix illegal option error on mac builds
  ports/stm32f4/Makefile
Labels: stm

#2173 STM32: Add OS and Struct support
  ports/stm32f4/common-hal/os/__init__.c
  ports/stm32f4/mpconfigport.mk
Labels: stm

#2184 Fail when boards are missing too
  tools/ci_new_boards_check.py
Labels: bug, tooling
