Repository adafruit/circuitpython, pull requests merged in 2019-04, with the labels that each got.

#1731 Improved readability of Single Byte Bounds code
  shared-module/displayio/Display.c
Labels: displayio, refactoring

#1743 A display fix and file system flush tweak
  ports/atmel-samd/supervisor/internal_flash.c
  ports/nrf/supervisor/internal_flash.c
  supervisor/flash.h
  supervisor/shared/display.c
  supervisor/shared/external_flash/external_flash.c
  supervisor/shared/filesystem.c
Labels: bug, crash, displayio

#1751 Allow parameter data to be treated as commands for the ssd1331
  ports/atmel-samd/boards/hallowing_m0_express/board.c
  ports/atmel-samd/boards/hallowing_m0_express/mpconfigboard.mk
  ports/atmel-samd/boards/pybadge/board.c
  ports/atmel-samd/boards/pyportal/board.c
  shared-bindings/displayio/Display.c
  shared-bindings/displayio/Display.h
  shared-module/displayio/Display.c
  shared-module/displayio/Display.h
Labels: displayio, enhancement

#1755 Always check TileGrid's x, y
  shared-bindings/displayio/TileGrid.c
Labels: bug, crash

#1758 Stop hard-coding SPI frequency in FourWire
  ports/atmel-samd/boards/hallowing_m0_express/board.c
  ports/atmel-samd/common-hal/busio/SPI.c
  ports/nrf/common-hal/busio/SPI.c
  shared-bindings/busio/SPI.h
  shared-module/displayio/FourWire.c
  shared-module/displayio/FourWire.h
Labels: displayio, enhancement

#1772 Check that a never free pointer is on the heap.
  ports/atmel-samd/boards/itsybitsy_m0_express/mpconfigboard.h
  ports/atmel-samd/boards/sparkfun_lumidrive/mpconfigboard.mk
  py/gc.c
Labels: bug, crash, displayio

#1774 Tweak pybadge and fix display bugs
  .gitignore
  locale/ID.po
  locale/circuitpython.pot
  locale/de_DE.po
  locale/en_US.po
  locale/en_x_pirate.po
  locale/es.po
  locale/fil.po
  locale/fr.po
  locale/it_IT.po
  locale/pl.po
  locale/pt_BR.po
  ports/atmel-samd/boards/itsybitsy_m0_express/mpconfigboard.mk
  py/objtype.c
  shared-bindings/displayio/Display.c
  shared-bindings/displayio/TileGrid.c
Labels: bug, displayio

#1781 Add alias support for unique board revs
  tools/build_board_info.py
  tools/build_release_files.py
Labels: enhancement, tooling

#1802 Revert "nrf nvm: touchups to nickzoic PR #1768"
  ports/nrf/Makefile
  ports/nrf/boards/adafruit_nrf52840_s140_v6.ld
  ports/nrf/boards/feather_nrf52840_express/mpconfigboard.h
  ports/nrf/common-hal/microcontroller/__init__.c
  ports/nrf/common-hal/nvm/ByteArray.c
  ports/nrf/common-hal/nvm/ByteArray.h
  ports/nrf/common-hal/nvm/__init__.c
  ports/nrf/mpconfigport.mk
  ports/nrf/peripherals/nrf/nvm.c
  ports/nrf/peripherals/nrf/nvm.h
  ports/nrf/supervisor/internal_flash.c
  ports/nrf/supervisor/internal_flash.h
Labels: nrf52

#1805 Doc updates for 4.0.0
  .travis.yml
  CONTRIBUTING.md
  README.rst
  conf.py
  logo/license-MIT-brightgreen.svg
Labels: documentation

#1809 Unify VM cleanup code
  main.c
Labels: crash, supervisor

#1810 Fix off by one error in OnDiskBitmap
  shared-module/displayio/OnDiskBitmap.c
Labels: bug, displayio

#1811 Tweak RTD to install svg2pdfconverter
  .readthedocs.yml
  docs/requirements.txt
Labels: bug, documentation

#1815 Turn off auto_brightness if brightness is set
  ports/atmel-samd/boards/hallowing_m0_express/board.c
  ports/atmel-samd/boards/pybadge/board.c
  ports/atmel-samd/boards/pyportal/board.c
  ports/atmel-samd/boards/ugame10/board.c
  shared-bindings/displayio/Display.c
  shared-bindings/displayio/Display.h
  shared-module/displayio/Display.c
Labels: bug, circuitpython api, displayio

#1816 Correct collect of permanent pointers.
  py/gc.c
Labels: bug, crash, displayio

#1827 Add Electronut to build automatically
  .travis.yml
Labels: nrf52, tooling
