Repository adafruit/circuitpython, pull requests merged in 2019-01, with the labels that each got.

#1442 Initial pass at pyportal board define.
  .travis.yml
  ports/atmel-samd/boards/pyportal/board.c
  ports/atmel-samd/boards/pyportal/mpconfigboard.h
  ports/atmel-samd/boards/pyportal/mpconfigboard.mk
  ports/atmel-samd/boards/pyportal/pins.c
Labels: atmel-samd

#1467 Remove ESP8266 build
  .travis.yml
  tools/build_board_info.py
Labels: esp8266

#1487 Enable displayio on all Express boards.
  ports/atmel-samd/boards/circuitplayground_express/mpconfigboard.h
  ports/atmel-samd/boards/circuitplayground_express_crickit/mpconfigboard.h
  ports/atmel-samd/boards/feather_m0_express_crickit/mpconfigboard.h
  ports/atmel-samd/mpconfigport.h
Labels: displayio

#1492 Fix board info script to skip removed boards.
  tools/build_board_info.py
Labels: bug, tooling

#1502 Remove draft because is unpublishes releases
  .travis.yml
Labels: tooling

#1499 Nickzoic/circuitpython nrf touchin 1048
  ports/nrf/Makefile
  ports/nrf/common-hal/touchio/TouchIn.c
  ports/nrf/common-hal/touchio/TouchIn.h
  ports/nrf/common-hal/touchio/__init__.c
  ports/nrf/mpconfigport.h
Labels: circuitpython api, nrf52

#1506 All files for SparkFun LumiDrive and Redboard Turbo
  .travis.yml
  ports/atmel-samd/boards/sparkfun_lumidrive/board.c
  ports/atmel-samd/boards/sparkfun_lumidrive/mpconfigboard.h
  ports/atmel-samd/boards/sparkfun_lumidrive/mpconfigboard.mk
  ports/atmel-samd/boards/sparkfun_lumidrive/pins.c
  ports/atmel-samd/boards/sparkfun_redboard_turbo/board.c
  ports/atmel-samd/boards/sparkfun_redboard_turbo/mpconfigboard.h
  ports/atmel-samd/boards/sparkfun_redboard_turbo/mpconfigboard.mk
  ports/atmel-samd/boards/sparkfun_redboard_turbo/pins.c
  supervisor/shared/external_flash/devices.h
Labels: atmel-samd
