Repository adafruit/circuitpython, pull requests merged in 2019-12, with the labels that each got.

#2350 Fix for neopixels on <100MHz STM32 boards
  ports/stm32f4/common-hal/digitalio/DigitalInOut.c
  ports/stm32f4/common-hal/neopixel_write/__init__.c
Labels: stm

#2356 Add connection interval and debugging
  .gitmodules
  ports/nrf/bluetooth/ble_drv.c
  ports/nrf/common-hal/_bleio/Adapter.c
  ports/nrf/common-hal/_bleio/Connection.c
  ports/nrf/common-hal/_bleio/Connection.h
  ports/nrf/common-hal/_bleio/Service.c
  ports/nrf/common-hal/_bleio/__init__.c
  py/circuitpy_mpconfig.h
  shared-bindings/_bleio/Connection.c
  shared-bindings/_bleio/Connection.h
  shared-bindings/displayio/OnDiskBitmap.c
  supervisor/shared/bluetooth.c
Labels: circuitpython api, enhancement, nrf52

#2362 Check connection validity after service discovery.
  ports/nrf/bluetooth/ble_drv.c
  ports/nrf/common-hal/_bleio/Connection.c
  shared-bindings/_bleio/Connection.c
  shared-bindings/_bleio/Connection.h
  shared-bindings/_bleio/Service.c
Labels: bug, crash, nrf52

#2301 Add support for extended (>31 byte) BLE advertisements.
  ports/nrf/common-hal/_bleio/Adapter.c
  shared-bindings/_bleio/Adapter.c
Labels: enhancement, nrf52

#2364 nRF: PWMAudioOut: fix half-speed playback of stereo samples
  ports/nrf/common-hal/audiopwmio/PWMAudioOut.c
  ports/nrf/common-hal/audiopwmio/PWMAudioOut.h
Labels: audioio, bug, nrf52

#2369 Fix crashes while copying files to nRF via USB
  py/gc.c
  supervisor/shared/external_flash/external_flash.c
Labels: bug, crash, nrf52

#2406 Improve USB eject by resetting on replug
  supervisor/shared/usb/usb.c
  supervisor/shared/usb/usb_msc_flash.c
  supervisor/usb.h
Labels: bug, crash, usb

#2403 Switch to fetching GCC from AWS
  .github/workflows/build.yml
Labels: tooling

#2440 Fix Hallowing M4 Express UART pin mapping
  ports/atmel-samd/boards/hallowing_m4_express/mpconfigboard.h
  ports/atmel-samd/boards/hallowing_m4_express/pins.c
Labels: atmel-samd, bug
