Repository adafruit/circuitpython, pull requests merged in 2020-01, with the labels that each got.

#2034 Updates to pixelbuf API - Addresses #884
  extmod/modbtree.c
  extmod/moductypes.c
  locale/ID.po
  locale/circuitpython.pot
  locale/de_DE.po
  locale/en_US.po
  locale/en_x_pirate.po
  locale/es.po
  locale/fil.po
  locale/fr.po
  locale/it_IT.po
  locale/ko.po
  locale/pl.po
  locale/pt_BR.po
  locale/zh_Latn_pinyin.po
  py/obj.c
  py/objlist.c
  py/objnamedtuple.c
  py/objnamedtuple.h
  py/objtuple.c
  py/objtype.c
  shared-bindings/_pixelbuf/PixelBuf.c
  shared-bindings/_pixelbuf/PixelBuf.h
  shared-bindings/_pixelbuf/__init__.c
  shared-bindings/_pixelbuf/__init__.h
  shared-bindings/_pixelbuf/types.h
  shared-module/_pixelbuf/PixelBuf.c
  shared-module/_pixelbuf/PixelBuf.h
Labels: circuitpython api, performance

#2432 Fix nRF UART reset
  ports/nrf/common-hal/busio/I2C.c
  ports/nrf/common-hal/busio/SPI.c
  ports/nrf/common-hal/busio/UART.c
  ports/nrf/common-hal/neopixel_write/__init__.c
Labels: bug, nrf52

#2459 STM32: Allow simplex SPI
  ports/stm32f4/common-hal/busio/SPI.c
Labels: stm

#2501 Fix board_timerhook
  ports/cxd56/Makefile
Labels: bug, spresense

#2510 nrf: Add bonding to BLE pairing support
  locale/circuitpython.pot
  ports/atmel-samd/common-hal/nvm/ByteArray.c
  ports/nrf/Makefile
  ports/nrf/background.c
  ports/nrf/common-hal/_bleio/Adapter.c
  ports/nrf/common-hal/_bleio/Characteristic.c
  ports/nrf/common-hal/_bleio/Connection.c
  ports/nrf/common-hal/_bleio/Connection.h
  ports/nrf/common-hal/_bleio/__init__.c
  ports/nrf/common-hal/_bleio/__init__.h
  ports/nrf/common-hal/_bleio/bonding.c
  ports/nrf/common-hal/_bleio/bonding.h
  ports/nrf/common-hal/nvm/ByteArray.c
  ports/nrf/mpconfigport.h
  ports/nrf/peripherals/nrf/nvm.c
  ports/nrf/peripherals/nrf/nvm.h
  py/gc.c
  py/gc.h
  shared-bindings/_bleio/Adapter.c
  shared-bindings/_bleio/Adapter.h
  shared-bindings/_bleio/Characteristic.c
Labels: enhancement, nrf52

#2530 mimxrt1011: Fix pin definition
  ports/mimxrt10xx/peripherals/mimxrt10xx/MIMXRT1011/pins.c
Labels: mimxrt10xx

#2541 Update fix (missing pragma gcc diagnostic push)
  py/emitnative.c
Labels: bug
