Repository adafruit/circuitpython, pull requests merged in 2021-05, with the labels that each got.

#4650 wifi.radio Access Point modes
  locale/circuitpython.pot
  ports/esp32s2/common-hal/wifi/Network.c
  ports/esp32s2/common-hal/wifi/Radio.c
  ports/esp32s2/common-hal/wifi/Radio.h
  ports/esp32s2/common-hal/wifi/__init__.c
  shared-bindings/wifi/AuthMode.h
  shared-bindings/wifi/Radio.c
  shared-bindings/wifi/Radio.h
  shared-bindings/wifi/__init__.c
Labels: enhancement, esp32s2, network

#4719 Espruino Pico: Remove settings for DNP oscillator
  ports/stm/boards/espruino_pico/mpconfigboard.h
Labels: stm

#4725 Add Python helper tool for MicroPython merges.
  tools/merge_micropython.py
Labels: tooling

#4754 Fix endpoint checking; Clean up safe mode printing
  locale/ID.po
  locale/circuitpython.pot
  locale/de_DE.po
  locale/en_GB.po
  locale/es.po
  locale/fr.po
  locale/hi.po
  locale/ja.po
  locale/nl.po
  locale/pl.po
  locale/pt_BR.po
  locale/sv.po
  locale/zh_Latn_pinyin.po
  main.c
  ports/atmel-samd/mpconfigport.mk
  ports/cxd56/mpconfigport.mk
  ports/esp32s2/mpconfigport.mk
  ports/litex/mpconfigport.mk
  ports/mimxrt10xx/mpconfigport.mk
  ports/nrf/mpconfigport.mk
  ports/raspberrypi/mpconfigport.mk
  ports/stm/boards/espruino_pico/mpconfigboard.mk
  ports/stm/boards/pyb_nano_v2/mpconfigboard.mk
  ports/stm/boards/stm32f411ve_discovery/mpconfigboard.mk
  ports/stm/mpconfigport.mk
  py/circuitpy_mpconfig.mk
  shared-bindings/storage/__init__.c
  shared-bindings/usb_cdc/__init__.c
  shared-bindings/usb_hid/__init__.c
  shared-bindings/usb_midi/__init__.c
  shared-module/storage/__init__.c
  shared-module/storage/__init__.h
  shared-module/usb_cdc/__init__.c
  shared-module/usb_cdc/__init__.h
  shared-module/usb_hid/__init__.c
  shared-module/usb_hid/__init__.h
  shared-module/usb_midi/__init__.c
  shared-module/usb_midi/__init__.h
  supervisor/shared/safe_mode.c
  supervisor/shared/usb/usb_desc.c
  supervisor/usb.h
Labels: usb

#4773 Implement pulseout for RP2040
  ports/raspberrypi/Makefile
  ports/raspberrypi/common-hal/pulseio/PulseOut.c
  ports/raspberrypi/common-hal/pulseio/PulseOut.h
Labels: rp2

#4779 Fix safe mode on rp2040
  .github/workflows/build.yml
  ports/raspberrypi/supervisor/port.c
  supervisor/shared/safe_mode.c
Labels: bug, rp2

#3493 Implemented the ability to set the transmitter power on nRF52 devices
  devices/ble_hci/common-hal/_bleio/Adapter.c
  locale/circuitpython.pot
  ports/nrf/common-hal/_bleio/Adapter.c
  ports/nrf/common-hal/_bleio/__init__.c
  shared-bindings/_bleio/Adapter.c
  shared-bindings/_bleio/Adapter.h
Labels: enhancement, nrf52

#4783 Fix safe mode on rp2040 (in 7.x)
  ports/raspberrypi/supervisor/port.c
  supervisor/shared/safe_mode.c
Labels: bug, rp2

#4606 Internal API revisions to sleep
  main.c
  ports/esp32s2/common-hal/alarm/__init__.c
  ports/esp32s2/common-hal/alarm/pin/PinAlarm.c
  ports/esp32s2/common-hal/alarm/pin/PinAlarm.h
  ports/esp32s2/common-hal/alarm/time/TimeAlarm.c
  ports/esp32s2/common-hal/alarm/time/TimeAlarm.h
  ports/esp32s2/common-hal/alarm/touch/TouchAlarm.c
  ports/esp32s2/common-hal/alarm/touch/TouchAlarm.h
  ports/nrf/common-hal/alarm/__init__.c
  ports/nrf/common-hal/alarm/pin/PinAlarm.c
  ports/nrf/common-hal/alarm/pin/PinAlarm.h
  ports/nrf/common-hal/alarm/time/TimeAlarm.c
  ports/nrf/common-hal/alarm/time/TimeAlarm.h
  ports/nrf/common-hal/alarm/touch/TouchAlarm.c
  ports/nrf/common-hal/alarm/touch/TouchAlarm.h
  ports/stm/common-hal/alarm/__init__.c
  ports/stm/common-hal/alarm/pin/PinAlarm.c
  ports/stm/common-hal/alarm/pin/PinAlarm.h
  ports/stm/common-hal/alarm/time/TimeAlarm.c
  ports/stm/common-hal/alarm/time/TimeAlarm.h
  shared-bindings/alarm/__init__.c
  shared-bindings/alarm/__init__.h
Labels: advanced api, power

#4743 Simplify the status LED to save power
  main.c
  ports/atmel-samd/boards/feather_m4_can/mpconfigboard.h
  ports/atmel-samd/boards/feather_m4_express/mpconfigboard.h
  ports/atmel-samd/boards/picoplanet/mpconfigboard.h
  ports/atmel-samd/boards/qtpy_m0/board.c
  ports/atmel-samd/boards/qtpy_m0/mpconfigboard.h
  ports/atmel-samd/boards/qtpy_m0_haxpress/board.c
  ports/atmel-samd/boards/qtpy_m0_haxpress/mpconfigboard.h
  ports/atmel-samd/common-hal/busio/SPI.c
  ports/atmel-samd/common-hal/microcontroller/Pin.c
  ports/atmel-samd/common-hal/microcontroller/Pin.h
  ports/atmel-samd/common-hal/neopixel_write/__init__.c
  ports/atmel-samd/supervisor/internal_flash.c
  ports/atmel-samd/supervisor/port.c
  ports/esp32s2/boards/adafruit_feather_esp32s2_nopsram/mpconfigboard.h
  ports/esp32s2/boards/adafruit_feather_esp32s2_tftback_nopsram/mpconfigboard.h
  ports/esp32s2/boards/adafruit_magtag_2.9_grayscale/mpconfigboard.h
  ports/esp32s2/boards/adafruit_magtag_2.9_grayscale/pins.c
  ports/esp32s2/boards/unexpectedmaker_tinys2/mpconfigboard.h
  ports/esp32s2/common-hal/busio/SPI.c
  ports/esp32s2/common-hal/microcontroller/Pin.c
  ports/esp32s2/common-hal/microcontroller/Pin.h
  ports/mimxrt10xx/common-hal/microcontroller/Pin.c
  ports/mimxrt10xx/common-hal/microcontroller/Pin.h
  ports/nrf/boards/makerdiary_m60_keyboard/mpconfigboard.h
  ports/nrf/boards/makerdiary_nrf52840_m2_devkit/mpconfigboard.h
  ports/nrf/boards/particle_xenon/mpconfigboard.h
  ports/nrf/common-hal/microcontroller/Pin.c
  ports/nrf/common-hal/microcontroller/Pin.h
  ports/raspberrypi/boards/adafruit_itsybitsy_rp2040/board.c
  ports/raspberrypi/boards/adafruit_itsybitsy_rp2040/mpconfigboard.h
  ports/raspberrypi/boards/adafruit_qtpy_rp2040/board.c
  ports/raspberrypi/boards/adafruit_qtpy_rp2040/mpconfigboard.h
  ports/raspberrypi/common-hal/busio/SPI.c
  ports/raspberrypi/common-hal/microcontroller/Pin.c
  ports/raspberrypi/common-hal/microcontroller/Pin.h
  ports/stm/common-hal/alarm/__init__.c
  ports/stm/common-hal/alarm/__init__.h
  ports/stm/common-hal/microcontroller/Pin.c
  ports/stm/common-hal/microcontroller/Pin.h
  ports/stm/common-hal/microcontroller/Processor.c
  py/circuitpy_mpconfig.h
  shared-bindings/supervisor/__init__.c
  shared-module/displayio/EPaperDisplay.c
  shared-module/displayio/EPaperDisplay.h
  supervisor/shared/external_flash/external_flash.c
  supervisor/shared/rgb_led_colors.h
  supervisor/shared/rgb_led_status.c
  supervisor/shared/rgb_led_status.h
  supervisor/shared/safe_mode.c
  supervisor/shared/status_leds.c
  supervisor/shared/status_leds.h
  supervisor/supervisor.mk
Labels: breaks api

#4763 Add build_memory_info for esp32s2
  ports/esp32s2/.gitignore
  ports/esp32s2/Makefile
  ports/esp32s2/tools/build_memory_info.py
Labels: esp32s2, tooling

#4772 [resolves #4771] DEBUG UART supported on ATMSAME5x
  ports/atmel-samd/common-hal/busio/UART.c
  supervisor/shared/serial.c
Labels: atmel-samd, bug
