Repository adafruit/circuitpython, pull requests merged in 2021-02, with the labels that each got.

#4095 Fix default socket timeout
  ports/esp32s2/common-hal/socketpool/Socket.c
  ports/esp32s2/common-hal/socketpool/SocketPool.c
Labels: esp32s2, network

#4083 RP2040: Support for WatchDog
  Makefile
  locale/circuitpython.pot
  ports/raspberrypi/common-hal/microcontroller/__init__.c
  ports/raspberrypi/common-hal/watchdog/WatchDogMode.c
  ports/raspberrypi/common-hal/watchdog/WatchDogTimer.c
  ports/raspberrypi/common-hal/watchdog/WatchDogTimer.h
  ports/raspberrypi/common-hal/watchdog/__init__.c
  ports/raspberrypi/mpconfigport.mk
Labels: rp2

#4105 Add board Silicognition LLC M4-Shim
  .github/workflows/build.yml
  ports/atmel-samd/boards/silicognition-m4-shim/board.c
  ports/atmel-samd/boards/silicognition-m4-shim/mpconfigboard.h
  ports/atmel-samd/boards/silicognition-m4-shim/mpconfigboard.mk
  ports/atmel-samd/boards/silicognition-m4-shim/pins.c
Labels: board

#4087 Fixing microcontroller.cpu on multi-core cpus and adding microcontroller.cpus
  ports/raspberrypi/common-hal/microcontroller/__init__.c
  shared-bindings/microcontroller/Processor.c
  shared-bindings/microcontroller/__init__.c
  shared-bindings/microcontroller/__init__.h
Labels: circuitpython api, enhancement

#4096 Translations update from Weblate
  locale/ID.po
  locale/cs.po
  locale/de_DE.po
  locale/el.po
  locale/es.po
  locale/fil.po
  locale/fr.po
  locale/hi.po
  locale/it_IT.po
  locale/ja.po
  locale/ko.po
  locale/nl.po
  locale/pl.po
  locale/pt_BR.po
  locale/sv.po
  locale/zh_Latn_pinyin.po
Labels: internationalization

#4018 add uart hardware flow control to nrf port
  locale/circuitpython.pot
  ports/nrf/boards/simmel/mpconfigboard.mk
  ports/nrf/common-hal/busio/UART.c
  ports/nrf/common-hal/busio/UART.h
Labels: enhancement, nrf52

#4114 Add .spi accessor to SPIDevice
  shared-bindings/adafruit_bus_device/SPIDevice.c
  shared-bindings/adafruit_bus_device/SPIDevice.h
  shared-module/adafruit_bus_device/SPIDevice.c
Labels: bug, circuitpython api

#4126 WebUSB serial support (compile-time option, currently defaulted to OFF)
  WEBUSB_README.md
  docs/index.rst
  ports/esp32s2/Makefile
  ports/esp32s2/boards/espressif_kaluga_1/mpconfigboard.mk
  ports/esp32s2/mpconfigport.mk
  py/circuitpy_defns.mk
  py/circuitpy_mpconfig.mk
  supervisor/shared/serial.c
  supervisor/shared/usb/tusb_config.h
  supervisor/shared/usb/usb.c
  supervisor/supervisor.mk
  tools/gen_usb_descriptor.py
Labels: enhancement, usb

#4128 ESP32S2: Add I2S pin claiming
  ports/esp32s2/common-hal/audiobusio/I2SOut.c
Labels: esp32s2

#4125 Add A3 pin to Raspberry Pi Pico
  ports/raspberrypi/boards/raspberry_pi_pico/pins.c
Labels: rp2

#4137 Add SMPS mode pin to Raspi Pico pins.c
  ports/raspberrypi/boards/raspberry_pi_pico/pins.c
Labels: enhancement, rp2

#4138 Socket: Fix LWIP connect error
  ports/esp32s2/common-hal/socketpool/Socket.c
Labels: esp32s2, network

#4136 Socket: fix inconsistencies in argument types
  locale/circuitpython.pot
  ports/esp32s2/common-hal/socketpool/Socket.c
  ports/esp32s2/common-hal/ssl/SSLSocket.c
  shared-bindings/socketpool/Socket.c
  shared-bindings/socketpool/Socket.h
  shared-bindings/ssl/SSLSocket.c
  shared-bindings/ssl/SSLSocket.h
Labels: network

#4139 Socket: Connect accepted sockets
  ports/esp32s2/common-hal/socketpool/Socket.c
Labels: esp32s2, network

#4168 Add DynaLoRa-USB Dongle
  .github/workflows/build.yml
  ports/atmel-samd/boards/dynalora_usb/board.c
  ports/atmel-samd/boards/dynalora_usb/mpconfigboard.h
  ports/atmel-samd/boards/dynalora_usb/mpconfigboard.mk
  ports/atmel-samd/boards/dynalora_usb/pins.c
Labels: board

#4213 raspberrypi: implement os.urandom
  extmod/crypto-algorithms/sha256.c
  ports/raspberrypi/Makefile
  ports/raspberrypi/common-hal/os/__init__.c
Labels: enhancement, rp2

#4169 STM32: Fix I2C repeated start by converting to IT mode
  ports/stm/boards/espruino_pico/mpconfigboard.mk
  ports/stm/common-hal/busio/I2C.c
  ports/stm/common-hal/busio/I2C.h
  ports/stm/mpconfigport.h
Labels: stm

#4219 Add Bit transpose function to support piopixl8
  locale/circuitpython.pot
  ports/raspberrypi/mpconfigport.mk
  py/circuitpy_defns.mk
  py/circuitpy_mpconfig.h
  py/circuitpy_mpconfig.mk
  shared-bindings/bitops/__init__.c
  shared-bindings/bitops/__init__.h
  shared-module/bitops/__init__.c
  shared-module/bitops/__init__.h
Labels: enhancement

#4187 Create tests/_manual, add Socket tests
  tests/circuitpython-manual/audiocore/jeplayer-splash-16000-16bit-mono-signed.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-16000-16bit-stereo-signed.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-16000-24bit-mono-signed.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-16000-24bit-stereo-signed.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-16000-8bit-mono-unsigned.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-16000-8bit-stereo-unsigned.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-44100-16bit-mono-signed.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-44100-16bit-stereo-signed.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-44100-24bit-mono-signed.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-44100-24bit-stereo-signed.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-44100-8bit-mono-unsigned.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-44100-8bit-stereo-unsigned.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-44100-stereo.mp3
  tests/circuitpython-manual/audiocore/jeplayer-splash-8000-16bit-mono-signed.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-8000-16bit-stereo-signed.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-8000-24bit-mono-signed.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-8000-24bit-stereo-signed.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-8000-8bit-mono-unsigned.wav
  tests/circuitpython-manual/audiocore/jeplayer-splash-8000-8bit-stereo-unsigned.wav
  tests/circuitpython-manual/audiopwmio/single_buffer_loop.py
  tests/circuitpython-manual/audiopwmio/wavefile_pause_resume.py
  tests/circuitpython-manual/audiopwmio/wavefile_playback.py
  tests/circuitpython-manual/socketpool/client/cpy-client.py
  tests/circuitpython-manual/socketpool/client/host-server.py
  tests/circuitpython-manual/socketpool/client/readme.md
  tests/circuitpython-manual/socketpool/datagram/ntp.py
  tests/circuitpython-manual/socketpool/datagram/readme.md
  tests/circuitpython-manual/socketpool/server/cpy-server.py
  tests/circuitpython-manual/socketpool/server/host-client.py
  tests/circuitpython-manual/socketpool/server/readme.md
Labels: network, testing

#4247 Board specific flash sizes for RP2040
  ports/raspberrypi/boards/adafruit_feather_rp2040/mpconfigboard.h
  ports/raspberrypi/boards/qtpy_rp2040/mpconfigboard.h
  ports/raspberrypi/boards/raspberry_pi_pico/mpconfigboard.h
  ports/raspberrypi/supervisor/internal_flash.c
Labels: rp2

#4251 Implement audiobusio and enhance PIO for it
  locale/circuitpython.pot
  ports/raspberrypi/audio_dma.c
  ports/raspberrypi/bindings/rp2pio/StateMachine.c
  ports/raspberrypi/bindings/rp2pio/StateMachine.h
  ports/raspberrypi/common-hal/audiobusio/I2SOut.c
  ports/raspberrypi/common-hal/audiobusio/I2SOut.h
  ports/raspberrypi/common-hal/audiobusio/PDMIn.c
  ports/raspberrypi/common-hal/audiobusio/PDMIn.h
  ports/raspberrypi/common-hal/audiobusio/__init__.c
  ports/raspberrypi/common-hal/neopixel_write/__init__.c
  ports/raspberrypi/common-hal/rp2pio/StateMachine.c
  ports/raspberrypi/common-hal/rp2pio/StateMachine.h
  ports/raspberrypi/mpconfigport.mk
  ports/raspberrypi/supervisor/port.c
  tests/circuitpython-manual/audiobusio/i2s_sample_loop.py
  tests/circuitpython-manual/audiobusio/pdmin_rms.py
Labels: audio, enhancement, rp2

#4253 Fix second shared PWM
  ports/raspberrypi/common-hal/pwmio/PWMOut.c
Labels: bug, rp2

#4224 RP2040: Support for UART
  locale/circuitpython.pot
  ports/atmel-samd/boards/catwan_usbstick/mpconfigboard.mk
  ports/mimxrt10xx/common-hal/busio/UART.c
  ports/nrf/common-hal/busio/UART.c
  ports/raspberrypi/common-hal/busio/UART.c
  ports/raspberrypi/common-hal/busio/UART.h
  ports/raspberrypi/supervisor/port.c
  py/gc.c
  py/malloc.c
  py/misc.h
  shared-bindings/busio/UART.c
  tests/circuitpython-manual/busio/uart_echo.py
Labels: enhancement, rp2
