Repository adafruit/circuitpython, pull requests merged in 2021-01, with the labels that each got.

#3903 ESP32-S2: Log all Wi-Fi events & remove unneeded call
  ports/esp32s2/common-hal/wifi/Radio.c
  ports/esp32s2/common-hal/wifi/__init__.c
Labels: esp32s2

#3659 module msgpack
  locale/circuitpython.pot
  ports/atmel-samd/boards/bdmicro_vina_d21/mpconfigboard.mk
  ports/atmel-samd/boards/circuitplayground_express/mpconfigboard.mk
  ports/atmel-samd/boards/circuitplayground_express_crickit/mpconfigboard.mk
  ports/atmel-samd/boards/circuitplayground_express_displayio/mpconfigboard.mk
  ports/atmel-samd/boards/feather_m0_express/mpconfigboard.mk
  ports/atmel-samd/boards/feather_m0_express_crickit/mpconfigboard.mk
  ports/atmel-samd/boards/feather_m0_supersized/mpconfigboard.mk
  ports/atmel-samd/boards/metro_m0_express/mpconfigboard.mk
  ports/atmel-samd/boards/qtpy_m0_haxpress/mpconfigboard.mk
  ports/atmel-samd/boards/snekboard/mpconfigboard.mk
  ports/atmel-samd/boards/sparkfun_redboard_turbo/mpconfigboard.mk
  ports/atmel-samd/boards/stackrduino_m0_pro/mpconfigboard.mk
  ports/cxd56/boards/spresense/mpconfigboard.mk
  ports/nrf/boards/pca10100/mpconfigboard.mk
  ports/nrf/boards/simmel/mpconfigboard.mk
  py/circuitpy_defns.mk
  py/circuitpy_mpconfig.h
  py/circuitpy_mpconfig.mk
  shared-bindings/msgpack/ExtType.c
  shared-bindings/msgpack/ExtType.h
  shared-bindings/msgpack/__init__.c
  shared-bindings/msgpack/__init__.h
  shared-module/msgpack/__init__.c
  shared-module/msgpack/__init__.h
  tests/extmod/umsgpack_pack.py
  tests/extmod/umsgpack_pack.py.ext
Labels: cpython api, enhancement

#3291 add robots.txt to specify doc versions to appear in search engines
  conf.py
  docs/robots.txt
Labels: documentation

#3954 ESP32-S2: added sys.platform
  ports/esp32s2/mpconfigport.h
Labels: esp32s2

#3992 wifi: more disconnect reasons for retries & include error code in exception
  locale/circuitpython.pot
  ports/esp32s2/common-hal/wifi/Radio.c
  ports/esp32s2/common-hal/wifi/__init__.c
  shared-bindings/wifi/Radio.c
  shared-bindings/wifi/Radio.h
Labels: esp32s2

#3980 ESP32-S2 update docs to match code usage of IPPROTO_*
  shared-bindings/socketpool/SocketPool.c
Labels: esp32s2

#3911 Update built-in help output for localization (Issue #3907)
  locale/circuitpython.pot
  ports/atmel-samd/boards/arduino_mkrzero/mpconfigboard.mk
  ports/atmel-samd/boards/feather_m0_adalogger/mpconfigboard.mk
  ports/atmel-samd/boards/gemma_m0/mpconfigboard.mk
  py/builtinhelp.c
Labels: internationalization

#4017 ESP32-S2 wifi radio: check whether already connected before trying to connect
  .github/workflows/build.yml
  locale/circuitpython.pot
  ports/esp32s2/common-hal/wifi/Radio.c
Labels: esp32s2

#4052 Fix DigitalInOut.pull on RP2040
  ports/atmel-samd/boards/circuitplayground_express_crickit/mpconfigboard.mk
  ports/atmel-samd/boards/qtpy_m0/mpconfigboard.mk
  ports/raspberrypi/common-hal/digitalio/DigitalInOut.c
Labels: bug, rp2

#4071 Raise an error on UART use
  ports/raspberrypi/common-hal/busio/UART.c
Labels: bug, rp2

#4047 Add initial ParallelBus support for ESP32-S2
  locale/circuitpython.pot
  ports/esp32s2/common-hal/displayio/ParallelBus.c
  ports/esp32s2/common-hal/displayio/ParallelBus.h
Labels: displayio, enhancement, esp32s2

#4080 Fix blinka release PR language list
  tools/build_board_info.py
Labels: bug, tooling
