Repository adafruit/circuitpython, pull requests merged in 2021-08, with the labels that each got.

#5093 CI: Add `Print failure info`
  .github/workflows/build.yml
Labels: tooling

#5089 Add ability to disable BLE workflow
  main.c
  ports/nrf/Makefile
  shared-bindings/supervisor/__init__.c
  shared-module/terminalio/Terminal.c
  supervisor/shared/bluetooth/bluetooth.c
  supervisor/shared/bluetooth/bluetooth.h
  supervisor/shared/bluetooth/serial.c
  supervisor/shared/display.c
  tools/gen_display_resources.py
  tools/safe_mode_finder.py
Labels: bug, nrf52, ble

#5102 Add WeAct manufacturer for STM32F411 blackpill boards
  ports/stm/boards/stm32f411ce_blackpill/mpconfigboard.mk
  ports/stm/boards/stm32f411ce_blackpill_with_flash/mpconfigboard.mk
Labels: stm, board

#5116 Fixes the MOSI and MISO pins mapping
  ports/esp32s2/boards/atmegazero_esp32s2/pins.c
Labels: esp32s2, board

#5110 Implement `traceback.format_exception`
  locale/circuitpython.pot
  py/builtinhelp.c
  py/mpprint.c
  py/mpprint.h
  py/obj.c
  py/obj.h
  py/objexcept.c
  shared-bindings/traceback/__init__.c
  shared-module/traceback/__init__.c
  supervisor/shared/translate.c
  supervisor/shared/translate.h
Labels: enhancement, cpython api

#5115 Add getpass module
  locale/circuitpython.pot
  ports/atmel-samd/boards/adafruit_proxlight_trinkey_m0/mpconfigboard.mk
  ports/atmel-samd/boards/sensebox_mcu/mpconfigboard.mk
  py/circuitpy_defns.mk
  py/circuitpy_mpconfig.h
  py/circuitpy_mpconfig.mk
  shared-bindings/getpass/__init__.c
  shared-module/getpass/__init__.c
  shared-module/getpass/__init__.h
Labels: enhancement, cpython api

#5114 Add Board bluemicro840
  .github/workflows/build.yml
  ports/nrf/boards/bluemicro840/board.c
  ports/nrf/boards/bluemicro840/mpconfigboard.h
  ports/nrf/boards/bluemicro840/mpconfigboard.mk
  ports/nrf/boards/bluemicro840/pins.c
Labels: board

#5099 Added definitions for some upcoming Pimoroni LED driver boards
  .github/workflows/build.yml
  ports/raspberrypi/boards/pimoroni_interstate75/board.c
  ports/raspberrypi/boards/pimoroni_interstate75/mpconfigboard.h
  ports/raspberrypi/boards/pimoroni_interstate75/mpconfigboard.mk
  ports/raspberrypi/boards/pimoroni_interstate75/pico-sdk-configboard.h
  ports/raspberrypi/boards/pimoroni_interstate75/pins.c
  ports/raspberrypi/boards/pimoroni_plasma2040/board.c
  ports/raspberrypi/boards/pimoroni_plasma2040/mpconfigboard.h
  ports/raspberrypi/boards/pimoroni_plasma2040/mpconfigboard.mk
  ports/raspberrypi/boards/pimoroni_plasma2040/pico-sdk-configboard.h
  ports/raspberrypi/boards/pimoroni_plasma2040/pins.c
Labels: board

#5100 Switch SAMD21 ticks to PER event
  lib/utils/pyexec.c
  ports/atmel-samd/audio_dma.c
  ports/atmel-samd/audio_dma.h
  ports/atmel-samd/boards/adafruit_proxlight_trinkey_m0/mpconfigboard.h
  ports/atmel-samd/boards/adafruit_proxlight_trinkey_m0/mpconfigboard.mk
  ports/atmel-samd/boards/arduino_mkr1300/mpconfigboard.h
  ports/atmel-samd/boards/arduino_nano_33_iot/mpconfigboard.h
  ports/atmel-samd/common-hal/pulseio/PulseIn.c
  ports/atmel-samd/supervisor/port.c
  py/circuitpy_mpconfig.mk
  shared-bindings/busio/SPI.c
  shared-bindings/busio/UART.c
Labels: bug, atmel-samd

#5147 Increase tx power for BLE workflow pairing
  supervisor/shared/bluetooth/bluetooth.c
Labels: ble

#5137 Codeformat version checking
  tools/codeformat.py
Labels: tooling

#5139 Move OneWire to `onewireio`
  ports/atmel-samd/common-hal/busio/OneWire.h
  ports/esp32s2/common-hal/busio/OneWire.h
  ports/mimxrt10xx/common-hal/busio/OneWire.h
  ports/nrf/common-hal/busio/OneWire.h
  ports/raspberrypi/common-hal/busio/OneWire.h
  py/circuitpy_defns.mk
  py/circuitpy_mpconfig.h
  py/circuitpy_mpconfig.mk
  shared-bindings/_bleio/Adapter.c
  shared-bindings/bitbangio/OneWire.c
  shared-bindings/bitbangio/__init__.c
  shared-bindings/busio/OneWire.h
  shared-bindings/busio/__init__.c
  shared-bindings/canio/__init__.c
  shared-bindings/keypad/EventQueue.c
  shared-bindings/onewireio/OneWire.c
  shared-bindings/onewireio/OneWire.h
  shared-bindings/onewireio/__init__.c
  shared-bindings/onewireio/__init__.h
  shared-bindings/traceback/__init__.c
  shared-module/bitbangio/OneWire.h
  shared-module/onewireio/OneWire.c
  shared-module/onewireio/OneWire.h
  shared-module/onewireio/__init__.c
Labels: circuitpython api, breaks api

#5152 Fix crash on raise of reload exception
  py/mpstate.h
  py/runtime.c
Labels: bug, crash

#5160 Removed default UART, SPI and I2C from Tiny2040 config
  ports/raspberrypi/boards/pimoroni_tiny2040/pins.c
Labels: board, rp2

#5174 Fix RP2040 I2C instance check
  ports/raspberrypi/common-hal/busio/I2C.c
Labels: bug, rp2

#5182 Check background pending before sleep
  ports/atmel-samd/supervisor/port.c
  ports/esp32s2/supervisor/port.c
  ports/mimxrt10xx/Makefile
  ports/mimxrt10xx/linking/common.ld
  ports/mimxrt10xx/supervisor/port.c
  ports/nrf/supervisor/port.c
  ports/raspberrypi/supervisor/port.c
  ports/stm/supervisor/port.c
  shared-bindings/storage/__init__.c
  supervisor/background_callback.h
  supervisor/shared/background_callback.c
  supervisor/shared/usb/usb.c
Labels: bug, usb

#5200 Remove `displayio_copy_coords` from shared-module displayio
  shared-module/displayio/__init__.c
Labels: displayio, refactoring

#5203 Use the modified args to sort in displayio.Group
  shared-bindings/displayio/Group.c
Labels: bug, displayio

#5077 Add atexit module
  lib/utils/pyexec.c
  lib/utils/pyexec.h
  locale/circuitpython.pot
  main.c
  ports/unix/mpconfigport.h
  py/circuitpy_defns.mk
  py/circuitpy_mpconfig.h
  py/circuitpy_mpconfig.mk
  shared-bindings/atexit/__init__.c
  shared-module/atexit/__init__.c
  shared-module/atexit/__init__.h
  tests/circuitpython/atexit_test.py
  tests/misc/sys_atexit.py
  tests/misc/sys_atexit.py.exp
  tests/unix/extra_coverage.py.exp
Labels: enhancement, cpython api

#5205 Deprecate Display's constructor arg set_vertical_scroll
  ports/atmel-samd/boards/hallowing_m0_express/board.c
  ports/atmel-samd/boards/hallowing_m4_express/board.c
  ports/atmel-samd/boards/monster_m4sk/board.c
  ports/atmel-samd/boards/pewpew_m4/board.c
  ports/atmel-samd/boards/pybadge/board.c
  ports/atmel-samd/boards/pygamer/board.c
  ports/atmel-samd/boards/pyportal/board.c
  ports/atmel-samd/boards/pyportal_titano/board.c
  ports/atmel-samd/boards/seeeduino_wio_terminal/board.c
  ports/atmel-samd/boards/ugame10/board.c
  ports/esp32s2/boards/adafruit_feather_esp32s2_tftback_nopsram/board.c
  ports/esp32s2/boards/adafruit_funhouse/board.c
  ports/esp32s2/boards/lilygo_ttgo_t8_s2_st7789/board.c
  ports/esp32s2/boards/morpheans_morphesp-240/board.c
  ports/nrf/boards/clue_nrf52840_express/board.c
  ports/nrf/boards/hiibot_bluefi/board.c
  ports/nrf/boards/makerdiary_nrf52840_m2_devkit/board.c
  ports/nrf/boards/ohs2020_badge/board.c
  ports/raspberrypi/boards/adafruit_macropad_rp2040/board.c
  ports/stm/boards/meowbit_v121/board.c
  shared-bindings/displayio/Display.c
  shared-bindings/displayio/Display.h
  shared-module/displayio/Display.c
Labels: displayio

#5210 Change optimizer option so RP2040 DEBUG builds work
  ports/raspberrypi/Makefile
Labels: tooling, rp2

#5214 Fix incorrect subscription in `usb_hid.Device` constructor
  shared-bindings/usb_hid/Device.c
Labels: bug, usb

#5219 Support multiple status dotstars
  ports/esp32s2/boards/adafruit_funhouse/mpconfigboard.h
  supervisor/shared/status_leds.c
Labels: bug, esp32s2

#5220 Allocate I2C mutex with IDF
  ports/esp32s2/common-hal/busio/I2C.c
  ports/esp32s2/common-hal/busio/I2C.h
Labels: bug, crash, displayio, esp32s2

#5255 Fix RP2 countio reset
  ports/raspberrypi/common-hal/countio/Counter.c
  ports/raspberrypi/common-hal/countio/Counter.h
  ports/raspberrypi/supervisor/port.c
Labels: bug, rp2

#5253 Fix GPIOTE crashes by checking everything is ok
  ports/nrf/common-hal/alarm/pin/PinAlarm.c
  ports/nrf/common-hal/countio/Counter.c
  ports/nrf/common-hal/microcontroller/Processor.c
  ports/nrf/common-hal/pulseio/PulseIn.c
  ports/nrf/common-hal/rotaryio/IncrementalEncoder.c
  ports/nrf/supervisor/port.c
  supervisor/shared/bluetooth/file_transfer.c
Labels: enhancement, nrf52, circuitpython api

#5271 Switch CircuitPython serial off Nordic UUIDs
  supervisor/shared/bluetooth/bluetooth.c
  supervisor/shared/bluetooth/serial.c
Labels: ble

#5273 Fix nrf light_sleep when on usb
  ports/nrf/common-hal/alarm/__init__.c
Labels: bug, nrf52, power

#5274 Convert more modules to use MP_REGISTER_MODULE
  py/circuitpy_mpconfig.h
  shared-bindings/_stage/__init__.c
  shared-bindings/neopixel_write/__init__.c
  shared-bindings/onewireio/__init__.c
  shared-bindings/ps2io/__init__.c
  shared-bindings/pulseio/__init__.c
  shared-bindings/pwmio/__init__.c
  shared-bindings/rainbowio/__init__.c
  shared-bindings/random/__init__.c
  shared-bindings/rgbmatrix/__init__.c
  shared-bindings/rotaryio/__init__.c
  shared-bindings/rtc/__init__.c
  shared-bindings/sdcardio/__init__.c
  shared-bindings/sharpdisplay/__init__.c
  shared-bindings/storage/__init__.c
  shared-bindings/struct/__init__.c
  shared-bindings/supervisor/__init__.c
  shared-bindings/synthio/__init__.c
  shared-bindings/touchio/__init__.c
  shared-bindings/traceback/__init__.c
  shared-bindings/usb_cdc/__init__.c
  shared-bindings/usb_hid/__init__.c
  shared-bindings/usb_midi/__init__.c
  shared-bindings/vectorio/__init__.c
Labels: enhancement, refactoring
