Repository adafruit/circuitpython, pull requests merged in 2021-12, with the labels that each got.

#5649 Run test for traceback module
  ports/unix/variants/coverage/mpconfigvariant.mk
  shared-bindings/traceback/__init__.c
  tests/circuitpython/traceback_test.py.exp
  tests/run-tests.py
  tests/unix/extra_coverage.py.exp
Labels: enhancement, tooling, testing

#5660 espressif: busio.SPI: Use SPI_DMA_CH_AUTO
  ports/espressif/common-hal/busio/SPI.c
Labels: bug, espressif, busio

#5681 Pass ci_fetch_deps.py the sha rather than ref
  .github/workflows/build.yml
  .github/workflows/create_website_pr.yml
  .github/workflows/ports_windows.yml
Labels: bug, tooling

#5687 Three more sha spots for CI
  .github/workflows/build.yml
Labels: tooling

#5701 Fetch tools/adabot submodule for website build
  tools/ci_fetch_deps.py
Labels: tooling

#5702 Exclude ci checks and tests from building boards
  tools/ci_set_matrix.py
Labels: tooling

#5709 vectorio: Add width and height properties to rectangle
  locale/circuitpython.pot
  shared-bindings/vectorio/Rectangle.c
  shared-bindings/vectorio/Rectangle.h
  shared-bindings/vectorio/VectorShape.c
  shared-module/vectorio/Rectangle.c
  shared-module/vectorio/Rectangle.h
Labels: enhancement, displayio

#5728 Support 32 bit color with vectorio
  shared-module/vectorio/VectorShape.c
Labels: bug, displayio

#5729 fix missing pintout. Closes #5720 .
  ports/nrf/boards/makerdiary_nrf52840_mdk_usb_dongle/pins.c
Labels: bug, nrf52, board

#5723 traceback: fix for crash on non-native exceptions
  py/objexcept.c
  py/objexcept.h
  shared-bindings/traceback/__init__.c
  tests/circuitpython/traceback_test.py
  tests/circuitpython/traceback_test.py.exp
Labels: bug, crash

#5735 Add alternative clock pin name to match silkscreen
  ports/raspberrypi/boards/adafruit_kb2040/pins.c
Labels: bug, board, rp2

#5749 Tilegrid size properties
  shared-bindings/displayio/TileGrid.c
  shared-bindings/displayio/TileGrid.h
  shared-module/displayio/TileGrid.c
Labels: enhancement, displayio

#5758 Revert "pin specific versions of cascadetoml & tomlkit, temporarily"
  requirements-dev.txt
Labels: tooling

#5766 Add sideset_enable support to PIO
  ports/raspberrypi/bindings/rp2pio/StateMachine.c
  ports/raspberrypi/bindings/rp2pio/StateMachine.h
  ports/raspberrypi/common-hal/audiobusio/I2SOut.c
  ports/raspberrypi/common-hal/audiobusio/PDMIn.c
  ports/raspberrypi/common-hal/imagecapture/ParallelImageCapture.c
  ports/raspberrypi/common-hal/neopixel_write/__init__.c
  ports/raspberrypi/common-hal/nvm/ByteArray.c
  ports/raspberrypi/common-hal/paralleldisplay/ParallelBus.c
  ports/raspberrypi/common-hal/pulseio/PulseIn.c
  ports/raspberrypi/common-hal/rotaryio/IncrementalEncoder.c
  ports/raspberrypi/common-hal/rp2pio/StateMachine.c
  ports/raspberrypi/common-hal/rp2pio/StateMachine.h
Labels: rp2

#5753 Add new board Seeed_XIAO_nRF52840
  ports/nrf/boards/Seeed_XIAO_nRF52840_Sense/board.c
  ports/nrf/boards/Seeed_XIAO_nRF52840_Sense/mpconfigboard.h
  ports/nrf/boards/Seeed_XIAO_nRF52840_Sense/mpconfigboard.mk
  ports/nrf/boards/Seeed_XIAO_nRF52840_Sense/pins.c
Labels: enhancement, board
