Repository adafruit/circuitpython, pull requests merged in 2021-09, with the labels that each got.

#5279 Add IO9 / VBAT_SENSE to lilygo-t8-s2-st7789
  ports/esp32s2/boards/lilygo_ttgo_t8_s2_st7789/pins.c
Labels: enhancement, esp32s2, board

#5285 update TileGrid docstrings to include OnDiskBitmap
  shared-bindings/displayio/TileGrid.c
Labels: documentation, displayio

#5293 Make `aesio` module full build dependent
  ports/atmel-samd/boards/kicksat-sprite/mpconfigboard.mk
  ports/atmel-samd/boards/pybadge/mpconfigboard.mk
  ports/atmel-samd/boards/pygamer/mpconfigboard.mk
  ports/atmel-samd/mpconfigport.mk
  ports/nrf/boards/pca10100/mpconfigboard.mk
  ports/stm/boards/espruino_pico/mpconfigboard.mk
  ports/stm/boards/meowbit_v121/mpconfigboard.mk
  ports/stm/boards/thunderpack_v11/mpconfigboard.mk
  py/circuitpy_mpconfig.mk
Labels: enhancement, circuitpython api

#5300 Fix incorrect use of allocate_memory()
  main.c
  shared-bindings/supervisor/__init__.c
Labels: bug, circuitpython api

#5312 Selectively build boards based on changed files
  .github/workflows/build.yml
  tools/ci_changed_board_list.py
  tools/ci_new_boards_check.py
Labels: enhancement, tooling

#5308 Revert localization of `REPL` messages
  lib/utils/pyexec.c
  locale/circuitpython.pot
  py/builtinhelp.c
Labels: bug, crash

#5321 Fix scanning after a peripheral bond has been made
  ports/nrf/common-hal/_bleio/Adapter.c
Labels: bug, nrf52, ble

#5319 Fix the nRF builds with GCC 11.2
  ports/nrf/Makefile
Labels: bug, nrf52, tooling

#5324 remove lingering reference to settings.py in docs
  README.rst
Labels: enhancement, documentation

#5322 Add required python packages to building docs
  BUILDING.md
Labels: enhancement, documentation

#5327 Consistently validate location on VectorShape
  shared-bindings/vectorio/Circle.c
  shared-bindings/vectorio/Polygon.c
  shared-bindings/vectorio/Rectangle.c
  shared-bindings/vectorio/VectorShape.c
  shared-bindings/vectorio/VectorShape.h
  shared-module/vectorio/Polygon.c
  shared-module/vectorio/VectorShape.c
Labels: bug, displayio

#5335 Update pins.c to match hmi devkit board
  ports/esp32s2/boards/espressif_hmi_devkit_1/pins.c
Labels: esp32s2, board

#5330 Update the docs for vectorio
  shared-bindings/vectorio/Circle.c
  shared-bindings/vectorio/Polygon.c
  shared-bindings/vectorio/Rectangle.c
  shared-bindings/vectorio/__init__.c
Labels: enhancement, documentation, displayio

#5341 Enable WFI for raspberrypi port
  ports/raspberrypi/supervisor/port.c
Labels: enhancement, power, rp2

#5333 Make `next_code_allocation` and `prev_traceback_allocation` movable
  main.c
  ports/atmel-samd/boards/arduino_mkr1300/mpconfigboard.mk
  ports/atmel-samd/boards/arduino_nano_33_iot/mpconfigboard.mk
  ports/atmel-samd/boards/arduino_zero/mpconfigboard.mk
  ports/atmel-samd/boards/sensebox_mcu/mpconfigboard.mk
  ports/nrf/boards/simmel/mpconfigboard.mk
  shared-bindings/supervisor/__init__.c
  supervisor/shared/memory.c
Labels: bug, supervisor

#5348 Clear the buffer byte between ATB and FTB
  py/gc.c
Labels: bug, crash, espressif

#5363 Remove leftover stop from I2C.writeto docs
  shared-bindings/bitbangio/I2C.c
  shared-bindings/busio/I2C.c
Labels: documentation

#5364 mp_hal_delay_ms: avoid overflow when scaling ticks
  supervisor/shared/tick.c
Labels: bug, rp2

#5373 Update Display.fill_row() to accept all WriteableBuffers
  shared-bindings/displayio/Display.c
Labels: enhancement, displayio

#5360 keypad: Event: add timestamp.
  shared-bindings/keypad/Event.c
  shared-bindings/keypad/Event.h
  shared-bindings/supervisor/__init__.c
  shared-bindings/supervisor/__init__.h
  shared-module/keypad/Event.c
  shared-module/keypad/Event.h
  shared-module/keypad/EventQueue.c
  shared-module/keypad/EventQueue.h
  shared-module/keypad/KeyMatrix.c
  shared-module/keypad/Keys.c
  shared-module/keypad/ShiftRegisterKeys.c
Labels: enhancement

#5376 Fix stubs upload to S3
  .github/workflows/build.yml
Labels: bug, tooling

#5385 condition for release version of stubs upload to pypi
  .github/workflows/build.yml
Labels: enhancement, tooling

#5386 CI: Bump esp-idf cache key
  .github/workflows/build.yml
Labels: bug, tooling

#5388 Fix espressif serial over uart
  ports/espressif/common-hal/busio/UART.c
  ports/espressif/common-hal/microcontroller/Pin.c
  ports/espressif/common-hal/microcontroller/Pin.h
Labels: bug, espressif, busio

#5396 Fix a critical "typo"
  ports/nrf/boards/makerdiary_nrf52840_mdk/mpconfigboard.h
Labels: bug, board

#5394 Add initial esp32c3 support
  ports/espressif/Makefile
  ports/espressif/common-hal/alarm/__init__.c
  ports/espressif/common-hal/alarm/pin/PinAlarm.c
  ports/espressif/common-hal/microcontroller/Processor.c
  ports/espressif/common-hal/microcontroller/__init__.c
  ports/espressif/common-hal/pulseio/PulseIn.c
  ports/espressif/common-hal/socketpool/Socket.c
  ports/espressif/esp-idf-config/esp32s2/sdkconfig.defaults
  ports/espressif/esp-idf-config/sdkconfig.defaults
  ports/espressif/esp32c3_fix.h
  ports/espressif/mpconfigport.mk
  ports/espressif/mphalport.c
  ports/espressif/peripherals/esp32c3/pins.c
  ports/espressif/peripherals/esp32c3/pins.h
  ports/espressif/peripherals/pins.h
  ports/espressif/supervisor/port.c
  ports/espressif/supervisor/usb.c
  shared-bindings/wifi/Radio.c
  shared-module/displayio/Display.c
  shared-module/displayio/EPaperDisplay.c
  shared-module/framebufferio/FramebufferDisplay.c
Labels: enhancement, espressif

#5417 Add `esp32c3` documentation in `readme`
  README.rst
  ports/espressif/README.rst
Labels: enhancement, documentation, espressif
