Repository adafruit/circuitpython, pull requests merged in 2022-03, with the labels that each got.

#6128 Fix SAMD51 builds on GCC11.2
  ports/atmel-samd/Makefile
Labels: tooling

#6176 Vectorio color index
  shared-bindings/vectorio/Circle.c
  shared-bindings/vectorio/Circle.h
  shared-bindings/vectorio/Polygon.c
  shared-bindings/vectorio/Polygon.h
  shared-bindings/vectorio/Rectangle.c
  shared-bindings/vectorio/Rectangle.h
  shared-module/vectorio/Circle.c
  shared-module/vectorio/Circle.h
  shared-module/vectorio/Polygon.c
  shared-module/vectorio/Polygon.h
  shared-module/vectorio/Rectangle.c
  shared-module/vectorio/Rectangle.h
  tests/vectorio/color_index.py
Labels: enhancement, displayio

#6190 Add ESP32-S3-USB-OTG board
  ports/espressif/boards/espressif_esp32s3_usb_otg_n8/board.c
  ports/espressif/boards/espressif_esp32s3_usb_otg_n8/mpconfigboard.h
  ports/espressif/boards/espressif_esp32s3_usb_otg_n8/mpconfigboard.mk
  ports/espressif/boards/espressif_esp32s3_usb_otg_n8/pins.c
  ports/espressif/boards/espressif_esp32s3_usb_otg_n8/sdkconfig
Labels: espressif, board, esp32-s3
