Repository adafruit/circuitpython, pull requests merged in 2022-11, with the labels that each got.

#7160 Add note about rust to BUILDING.md
  BUILDING.md
Labels: hacktoberfest-accepted

#7199 Enable `microcontroller.cpu.temperature` on esp32s3
  ports/espressif/common-hal/microcontroller/Processor.c
Labels: enhancement, esp32-s3

#7132 CI: Schedule PR jobs based on commit specific changes
  .github/workflows/build.yml
  tools/ci_changes_per_commit.py
  tools/ci_set_matrix.py
Labels: enhancement, tooling

#6217 Status LED on AI Thinker ESP32-C3 boards
  ports/espressif/boards/ai_thinker_esp32-c3s-2m/mpconfigboard.h
  ports/espressif/boards/ai_thinker_esp32-c3s/mpconfigboard.h
Labels: board

#7231 Compare against PR head commit instead of merge ref
  .github/workflows/build.yml
Labels: bug, tooling

#7235 Fix json parse issue in ci_set_matrix.py
  .github/workflows/build.yml
  tools/ci_set_matrix.py
Labels: bug, tooling

#7245 Simplify some ESP32-C3 board sdkconfig files
  ports/espressif/boards/adafruit_qtpy_esp32c3/sdkconfig
  ports/espressif/boards/beetle-esp32-c3/sdkconfig
  ports/espressif/boards/lolin_c3_mini/sdkconfig
  ports/espressif/boards/microdev_micro_c3/sdkconfig
  ports/espressif/esp-idf-config/sdkconfig-esp32c3.defaults
Labels: board, esp32-c3

#7162 add boards list to make error message
  ports/atmel-samd/Makefile
  ports/broadcom/Makefile
  ports/cxd56/Makefile
  ports/espressif/Makefile
  ports/litex/Makefile
  ports/mimxrt10xx/Makefile
  ports/nrf/Makefile
  ports/raspberrypi/Makefile
  ports/stm/Makefile
  py/circuitpy_mkenv.mk
Labels: enhancement, tooling, hacktoberfest-accepted
