Repository adafruit/circuitpython, pull requests merged in 2023-04, with the labels that each got.

#7836 RFC: Web Workflow reliability and performance improvements
  ports/espressif/common-hal/socketpool/Socket.c
  ports/espressif/common-hal/socketpool/Socket.h
  ports/raspberrypi/common-hal/socketpool/Socket.h
  supervisor/shared/web_workflow/web_workflow.c
  supervisor/shared/web_workflow/web_workflow.h
  supervisor/shared/web_workflow/websocket.c
  supervisor/shared/workflow.c
Labels: enhancement, espressif, web workflow

#7852 doc: urandom is supported on nRF boards
  CODE_OF_CONDUCT.md
  shared-bindings/os/__init__.c
Labels: bug, documentation

#7870 Fixed outdated reference link
  shared-bindings/onewireio/__init__.c
Labels: documentation

#7892 add minimum validation for tilegrid size in terminalio.Terminal
  shared-bindings/terminalio/Terminal.c
Labels: displayio

#7893 Fix RP2040 idle
  main.c
  ports/raspberrypi/supervisor/port.c
Labels: rp2
